---
title: Week 6
subtitle: Web Scrapping with Python `selenium`
date: 2026-02-23
from: markdown+emoji
---

In the week 6, we will continue our journey on web-scrapping with Python `selenium`.


## 🏫 Lecture Slides  

- **Lecture 4 — Scrapping Data with `selenium`**  
  [View Slides](../danl-lec/danl-210-lec-04-2026-0213.html){target="_blank"}  


🎥 Looking for lecture recordings? You can only find those on Brightspace.


## ✍️ Classwork

- **Classwork 4 - Scrapping Table Data with Python `selenium` with XPath approach**  
  [View Classwork](../danl-cw/danl-210-cw-04.html){target="_blank"} 

- **Classwork 5 - Scrapping Data with `selenium`**  
  [View Classwork](../danl-cw/danl-210-cw-05.html){target="_blank"} 


## 💬 Discussion

<font size = "5">Welcome to our Week 6 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Week 6.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) or peer classmate (@GitHub-Username) regarding the Week 6 materials or need clarification on any points, don't hesitate to ask here. 

Let's collaborate and learn from each other!
