---
title: Week 7
subtitle: Web Scrapping with Python `selenium`; Requesting Data with Python `requests` and APIs
date: 2026-03-02
from: markdown+emoji
---

In the week 7, we will wrap up our journey on web-scrapping with Python `selenium`, and will then move on the last part of data collection, requesting data with Python `requests` and APIs


## 🏫 Lecture Slides  

- **Lecture 4 — Scrapping Data with `selenium`**  
  [View Slides](../danl-lec/danl-210-lec-04-2026-0213.html){target="_blank"}  

- **Lecture 5 — Collecting Data with `requests` and APIs**  
  [View Slides](../danl-lec/danl-210-lec-05-2026-0304.html){target="_blank"}  

🎥 Looking for lecture recordings? You can only find those on Brightspace.


## ✍️ Classwork

- **Classwork 5 - Scrapping Quote Data with `selenium`**  
  [View Classwork](../danl-cw/danl-210-cw-05.html){target="_blank"} 
  
- **Classwork 6 - Scrapping Book Data with `selenium`**  
  [View Classwork](../danl-cw/danl-210-cw-06.html){target="_blank"} 
  
- **Classwork 7 - Scrapping Stock Data with `selenium`**  
  [View Classwork](../danl-cw/danl-210-cw-07.html){target="_blank"} 


## 💬 Discussion

<font size = "5">Welcome to our Week 7 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Week 7.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) or peer classmate (@GitHub-Username) regarding the Week 7 materials or need clarification on any points, don't hesitate to ask here. 

Let's collaborate and learn from each other!
