---
title: Classwork 8
subtitle: Scrapping Web-tables
date: 2025-03-10
execute: 
  eval: false
  echo: false
  warning: false
  message: false
  
from: markdown+emoji
---

```{r}
#| include: false

library(DT)
library(reticulate)
reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```


# Question 1.

- Store the table in the following webpage as a `pandas`' `DataFrame`:
  - [https://www.eia.gov/petroleum/gasdiesel/gaspump_hist.php](https://www.eia.gov/petroleum/gasdiesel/gaspump_hist.php)
  - To convert the abbreviated-month-and-year `string` into `datetime`, we can use the `format='%b-%y'` option in the `pd.to_datetime()` method

```{python}
#| eval: false
Series = pd.to_datetime(Series, format='%b-%y')
```

- Export the `DataFrame` as a CSV file.

*Answer*:
```{python}

```


<br><br>

# Question 2.
- Store each table in the following webpage as a `pandas`' `DataFrame`:
  - [https://www.geneseo.edu/business/student%20outcomes](https://www.geneseo.edu/business/student%20outcomes)

- To clean the table data, the following attribute and methods can be useful:
  - `DataFrame.iloc[0]` locates the first observation in `DataFrame`.
  - `DataFrame.drop( index = DataFrame.index[0] )` drops the first observation in `DataFrame`.
  - `Series.str.replace('A', 'B')` replaces "A" with "B" in `Series`.

- Export the `DataFrame` as a CSV file.

*Answer*:
```{python}

```


<br><br>



# Discussion

<font size = "5">Welcome to our Classwork 8 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Classwork 8.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) regarding the Classwork 8 materials or need clarification on any points, don't hesitate to ask here. 

All comments will be stored [here](https://github.com/bcdanl/210/discussions/).

Let's collaborate and learn from each other!


