---
title: Classwork 9
subtitle: "Collecting Data with Python `requests` and APIs"
date: 2026-03-06
execute: 
  eval: false
  echo: false
  warning: false
  message: false
  
from: markdown+emoji
---


```{r}
#| include: false

library(tidyverse)
library(DT)
library(reticulate)
reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```




# Question 1
Provide a Python code to get New York City air quality surveillance data using the following API endpoint:

[https://data.cityofnewyork.us/resource/c3uy-2p5r.json](https://data.cityofnewyork.us/resource/c3uy-2p5r.json)

-	Use the following query parameter dictionary in your request, which sets the **"$limit"** to control how many rows are returned:

```{.python}
# query parameters (e.g., limit rows)
param_dict = {
    "$limit": 100   # You can increase this to get more observations
}
```


*Answer*:
```{python}

```



<br><br>

# Question 2
- Use the FRED API to retrieve two macroeconomic indicators:
	1.	U.S. Real GDP (`series_id` = "GDPC1")
	2.	U.S. Unemployment Rate (`series_id` = "UNRATE")



*Answer*:
```{python}

```


<br><br>





# Discussion


<font size = "5">Welcome to our Classwork 9 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Classwork 9.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) regarding the Classwork 9 materials or need clarification on any points, don't hesitate to ask here. 

All comments will be stored [here](https://github.com/bcdanl/210-spr-2026-discussion/discussions).

Let's collaborate and learn from each other!


