---
title: Accessing and Analyzing US Census Data in R
subtitle: tidycensus
date: 2024-03-19
execute: 
  warning: false
  message: false
from: markdown+emoji

---

```{r}
#| include: false

library(tidycensus)
library(tidyverse)
library(ggthemes)
library(skimr)
library(hrbrthemes)
library(DT)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
census_api_key("9da09887e5e3b8aa681fb94f6da18b5999b66047")
```

# Basic usage of `tidycensus`
```{r}
age20 <- get_decennial(geography = "state", 
                       variables = "P13_001N", 
                       year = 2020,
                       sumfile = "dhc")

datatable(age20)
```


```{r}
#| fig-height: 12
age20 %>%
  ggplot(aes(x = value, y = reorder(NAME, value))) + 
  geom_point()
```


# Spatial data in tidycensus

```{r}
orange <- get_acs(
  state = "CA",
  county = "Orange",
  geography = "tract",
  variables = "B19013_001",
  geometry = TRUE,
  year = 2020
)
datatable(orange)
```


```{r}
orange %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma") +
  theme_map()
```


# Discussion


<font size = "5">Welcome to `tidycensus` Discussion Board! 👋 </font>

Let's collaborate and learn from each other!
